/* ============================================================
   Correspondance entre les clés du site et les textures du jeu.

   Les valeurs sont des chemins relatifs à assets/minecraft/textures/
   dans le .jar de Minecraft, SANS l'extension .png.

   `tint` : les textures d'herbe, de feuillage et de vignes sont
   livrées en niveaux de gris et colorées par le jeu selon le biome.
   On applique donc la teinte nous-mêmes, en CSS.
   ============================================================ */

/* clé = caractère utilisé dans les schémas de plans */
var MAP_BLOCS = {
  '#': 'block/oak_planks',
  'o': 'block/oak_log',
  'k': 'block/stripped_oak_log',
  'b': 'block/stone_bricks',
  'c': 'block/cobblestone',
  'm': 'block/mossy_stone_bricks',
  'd': 'block/polished_deepslate',
  'n': 'block/polished_blackstone',
  'a': 'block/sandstone',
  'r': 'block/nether_bricks',
  'q': 'block/quartz_block_side',
  'g': 'block/glass',
  'G': 'block/glass',
  'w': 'block/water_still',
  'l': 'block/lava_still',
  't': 'block/dirt',
  'f': 'block/farmland_moist',
  'e': 'block/grass_block_top',
  '%': 'block/oak_leaves',
  '*': 'block/lantern',
  'D': 'block/oak_door_bottom',
  '/': 'block/oak_planks',
  '-': 'block/smooth_stone_slab_side',
  '|': 'block/oak_planks',
  '+': 'block/oak_trapdoor',
  'W': 'block/white_wool',
  'L': 'block/ladder',
  'M': 'block/cobblestone',
  'O': 'block/obsidian',
  'A': 'block/sand',
  'B': 'block/stone',
  's': 'block/oak_planks',
  '@': 'block/spawner',
  '~': 'block/water_flow',
  'R': 'block/redstone_dust_dot',
  'X': 'block/redstone_torch',
  'Z': 'block/repeater',
  'V': 'block/comparator',
  'P': 'block/piston_side',
  'S': 'block/piston_top_sticky',
  'Q': 'block/observer_front',
  'H': 'block/hopper_outside',
  'E': 'block/barrel_side',
  'U': 'block/furnace_front',
  'Y': 'block/crafting_table_front',
  'I': 'block/iron_block',
  'J': 'block/slime_block',
  '=': 'block/rail',
  '_': 'block/smooth_stone',
  '!': 'block/lever',
  'T': 'block/hopper_outside',
  'K': 'block/note_block',
  'N': 'block/moss_block',
  'C': 'block/cauldron_side',
  'F': 'block/campfire_log',
  'p': 'block/cactus_side',
  'u': 'block/sugar_cane',
  'z': 'block/bamboo_stalk',
  'v': 'block/vine',
  'h': 'block/hay_block_side',
  'i': 'block/ice',
  'j': 'block/honey_block_side',
  'y': 'block/beehive_side',
  '&': 'block/bookshelf',
  '$': 'block/enchanting_table_side',
  '(': 'block/anvil',
  '<': 'block/red_wool',
  '{': 'block/composter_side',
  '}': 'block/bell_side',
  '>': 'block/iron_door_bottom',
  '?': 'block/brewing_stand_base',
  ',': 'block/dirt_path_top',
  ';': 'block/red_wool'
};

/* Textures livrées en niveaux de gris : le jeu les colore selon le biome */
var TEINTES = {
  'e': '#79c05a',   // herbe, teinte de plaine
  '%': '#59ae30',   // feuillage de chêne
  'v': '#48b518',   // vignes
  'w': '#3f76e4',   // eau (couleur par défaut)
  '~': '#3f76e4',   // eau courante
  'u': '#7fb238'    // canne à sucre
};

/* clé = identifiant d'item utilisé dans les recettes */
var MAP_ITEMS = {
  bois: 'block/oak_log',
  planche: 'block/oak_planks',
  baton: 'item/stick',
  pierre: 'block/stone',
  cobble: 'block/cobblestone',
  fer: 'item/iron_ingot',
  or: 'item/gold_ingot',
  diamant: 'item/diamond',
  netherite: 'item/netherite_ingot',
  cuivre: 'item/copper_ingot',
  cuivreLg: 'item/copper_ingot',
  redstone: 'item/redstone',
  lapis: 'item/lapis_lazuli',
  emeraude: 'item/emerald',
  charbon: 'item/coal',
  quartz: 'item/quartz',
  obsi: 'block/obsidian',
  silex: 'item/flint',
  ficelle: 'item/string',
  cuir: 'item/leather',
  plume: 'item/feather',
  oeuf: 'item/egg',
  ble: 'item/wheat',
  sucre: 'item/sugar',
  canne: 'item/sugar_cane',
  papier: 'item/paper',
  livre: 'item/book',
  livreEnc: 'item/enchanted_book',
  laine: 'block/white_wool',
  sable: 'block/sand',
  verre: 'block/glass',
  argile: 'item/clay_ball',
  argileB: 'block/terracotta',
  brique: 'item/brick',
  poudre: 'item/gunpowder',
  slime: 'item/slime_ball',
  perle: 'item/ender_pearl',
  blaze: 'item/blaze_rod',
  poudreBl: 'item/blaze_powder',
  larme: 'item/ghast_tear',
  os: 'item/bone',
  chair: 'item/rotten_flesh',
  araignee: 'item/spider_eye',
  cactus: 'block/cactus_side',
  champi: 'block/red_mushroom',
  bol: 'item/bowl',
  pomme: 'item/apple',
  amethyste: 'item/amethyst_shard',
  echo: 'item/echo_shard',
  cuivreB: 'block/copper_block',
  ferB: 'block/iron_block',
  orB: 'block/gold_block',
  diamB: 'block/diamond_block',
  citrouille: 'block/carved_pumpkin',
  citrouilleB: 'block/pumpkin_side',
  neige: 'block/snow',
  ame: 'block/soul_sand',
  ame_torch: 'block/soul_soil',
  tete: 'entity/skeleton/wither_skeleton',
  crampon: 'item/nautilus_shell',
  coeurMer: 'item/heart_of_the_sea',
  prisma: 'item/prismarine_shard',
  encre: 'item/ink_sac',
  encreLum: 'item/glow_ink_sac',
  miel: 'item/honey_bottle',
  cire: 'item/honeycomb',
  bambou: 'item/bamboo',
  fleche: 'item/arrow',
  bouteille: 'item/glass_bottle',
  nether: 'item/nether_wart',
  ecaille: 'item/armadillo_scute',
  scute: 'item/turtle_scute',
  membrane: 'item/phantom_membrane',
  pepite: 'item/gold_nugget',
  lait: 'item/milk_bucket',
  melon: 'item/melon_slice',
  carotte: 'item/carrot',
  cacao: 'item/cocoa_beans',
  dalle: 'block/smooth_stone_slab_side',
  dalleP: 'block/smooth_stone_slab_side',
  bibli: 'block/bookshelf',
  four: 'block/furnace_front',
  etabli: 'block/crafting_table_front',
  dropper: 'block/dropper_front',
  arc: 'item/bow',
  coffre: 'block/barrel_side',
  plaque: 'block/smooth_stone',
  piston: 'block/piston_side',
  torche: 'block/torch',
  torcheR: 'block/redstone_torch',
  torcheA: 'block/soul_torch',
  pierreL: 'block/smooth_stone',
  etoile: 'item/nether_star',
  scrap: 'item/netherite_scrap',
  gravier: 'block/gravel',
  colorant: 'item/purple_dye',
  debris: 'block/ancient_debris_side',
  fleur: 'block/poppy',
  fleurR: 'block/poppy',
  chaine: 'block/iron_chain',
  outil: 'item/iron_ingot',
  ressource: 'item/iron_ingot',
  bloc: 'block/stone',
  armeD: 'item/diamond_sword',
  modele: 'item/netherite_upgrade_smithing_template',
  chorus: 'item/popped_chorus_fruit',
  tige: 'item/breeze_rod',
  lourd: 'block/heavy_core',
  tnt: 'block/tnt_side',
  seau: 'item/bucket',
  oeil: 'item/ender_eye',
  carapace: 'item/shulker_shell',
  glowstone: 'block/glowstone',
  poudreLum: 'item/glowstone_dust',
  tesson: 'item/angler_pottery_sherd',
  foin: 'block/hay_block_side',
  boussole: 'item/compass_00',
  cadre: 'item/item_frame',
  charbonB: 'block/coal_block',
  banniere: 'entity/banner/base',
  /* le bouclier n'a pas de texture plate exploitable : aplat de couleur */
  disque: 'item/music_disc_13',
  lapinC: 'item/cooked_rabbit',
  patate: 'item/baked_potato'
};

if (typeof module !== 'undefined') {
  module.exports = { MAP_BLOCS, MAP_ITEMS, TEINTES };
}
